// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchedulerEngine.Infrastructure;

#nullable disable

namespace SchedulerEngine.Infrastructure.Migrations
{
    [DbContext(typeof(SchedulerEngineDbContext))]
    partial class SchedulerEngineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchedulerEngine.Core.Model.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("application_user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DigitalIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("digital_identity_id");

                    b.Property<string>("ExternalUserId")
                        .HasColumnType("text")
                        .HasColumnName("external_user_id");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("DigitalIdentityId")
                        .IsUnique();

                    b.HasIndex("LanguageId");

                    b.ToTable("application_user", "scheduler_engine");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.ContactMedium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("contact_medium_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("integer")
                        .HasColumnName("address_id");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("boolean")
                        .HasColumnName("is_preferred");

                    b.Property<int>("MediumType")
                        .HasColumnType("integer")
                        .HasColumnName("medium_type");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer")
                        .HasColumnName("party_id");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId");

                    b.HasIndex("PartyId");

                    b.ToTable("contact_medium", "scheduler_engine");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int>("CredentialType")
                        .HasColumnType("integer")
                        .HasColumnName("credential_type");

                    b.Property<Guid>("DigitalIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("digital_identity_id");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("TrustLevel")
                        .HasColumnType("integer")
                        .HasColumnName("trust_level");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("DigitalIdentityId");

                    b.ToTable("credential", "scheduler_engine");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.CredentialCharacteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("credential_characteristic_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId");

                    b.ToTable("credential_characteristic", "scheduler_engine");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("text")
                        .HasColumnName("customer_number");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<int>("PartyRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("party_role_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("PartyRoleId")
                        .IsUnique();

                    b.ToTable("customer", "scheduler_engine");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.DigitalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("digital_identity_id");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DigitalIdentityDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("digital_identity_date");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nickname")
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<int>("PartyRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("party_role_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("PartyRoleId")
                        .IsUnique();

                    b.ToTable("digital_identity", "scheduler_engine");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.Individual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("individual_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("CountryOfBirth")
                        .HasColumnType("text")
                        .HasColumnName("country_of_birth");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("death_date");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("family_name");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("given_name");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("text")
                        .HasColumnName("marital_status");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<string>("Nationality")
                        .HasColumnType("text")
                        .HasColumnName("nationality");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer")
                        .HasColumnName("party_id");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("text")
                        .HasColumnName("place_of_birth");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("ValidForEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_for_end");

                    b.Property<DateTime?>("ValidForStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_for_start");

                    b.HasKey("Id");

                    b.HasIndex("PartyId")
                        .IsUnique();

                    b.ToTable("individual", "scheduler_engine");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LanguageCd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_cd");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCd")
                        .IsUnique();

                    b.ToTable("language", "scheduler_engine");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = 0,
                            LanguageCd = "tr",
                            Name = "Türkçe",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = 0,
                            LanguageCd = "en",
                            Name = "English",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = 0,
                            LanguageCd = "ru",
                            Name = "Русский",
                            Status = 0
                        });
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.LocalizableFields", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("localizable_fields_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("EntityField")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_field");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("localizable_fields", "scheduler_engine");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntityField = "Name",
                            EntityType = "Status",
                            IsDeleted = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            EntityField = "Description",
                            EntityType = "Status",
                            IsDeleted = 0,
                            Status = 0
                        });
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.Localization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("localization_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("EntityField")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_field");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LanguageCd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_cd");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("localization", "scheduler_engine");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<long>("IdentityNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("identity_number");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<long>("MersisNo")
                        .HasColumnType("bigint")
                        .HasColumnName("mersis_no");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer")
                        .HasColumnName("party_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("TaxNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("tax_number");

                    b.Property<string>("TaxOffice")
                        .HasColumnType("text")
                        .HasColumnName("tax_office");

                    b.Property<string>("TradeName")
                        .HasColumnType("text")
                        .HasColumnName("trade_name");

                    b.Property<long>("TradeRegisterNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("trade_register_number");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("ValidForEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_for_end");

                    b.Property<DateTime?>("ValidForStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_for_start");

                    b.HasKey("Id");

                    b.HasIndex("PartyId")
                        .IsUnique();

                    b.ToTable("organization", "scheduler_engine");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.OrganizationLanguageRel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("organization_language_rel_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("OrganizationId", "LanguageId")
                        .IsUnique();

                    b.ToTable("organization_language_rel", "scheduler_engine");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.Party", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("party_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<int>("PartyType")
                        .HasColumnType("integer")
                        .HasColumnName("party_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("party", "scheduler_engine");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.PartyRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("party_role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer")
                        .HasColumnName("party_id");

                    b.Property<int>("PartyRoleTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("party_role_type_id");

                    b.Property<int?>("PartyRoleTypeId1")
                        .HasColumnType("integer")
                        .HasColumnName("party_role_type_id1");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("ValidForEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_for_end");

                    b.Property<DateTime?>("ValidForStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_for_start");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PartyId");

                    b.HasIndex("PartyRoleTypeId");

                    b.HasIndex("PartyRoleTypeId1");

                    b.ToTable("party_role", "scheduler_engine");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.PartyRoleAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("party_role_account_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency_code");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<int>("PartyRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("party_role_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PartyRoleId")
                        .IsUnique();

                    b.ToTable("party_role_account", "scheduler_engine");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.PartyRoleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("party_role_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<string>("PartyRoleTypeCd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("party_role_type_cd");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("party_role_type", "scheduler_engine");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = 0,
                            Name = "Site Yöneticis",
                            PartyRoleTypeCd = "SITE_ADMIN",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = 0,
                            Name = "Uygulama Kullanıcısı",
                            PartyRoleTypeCd = "USER",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = 0,
                            Name = "Müşteri",
                            PartyRoleTypeCd = "CUSTOMER",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = 0,
                            Name = "Fatura Hesabı",
                            PartyRoleTypeCd = "BILL_ACCOUNT",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = 0,
                            Name = "Dış servis hesabı",
                            PartyRoleTypeCd = "EXTERNAL_SERVICE",
                            Status = 0
                        });
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("refresh_token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("integer")
                        .HasColumnName("application_user_id");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("refresh_token", "scheduler_engine");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.RelatedParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("related_party_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer")
                        .HasColumnName("party_id");

                    b.Property<int>("RelatedPartyId")
                        .HasColumnType("integer")
                        .HasColumnName("related_to_party_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.HasIndex("RelatedPartyId");

                    b.ToTable("related_party", "scheduler_engine");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.ServiceRecurringJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("service_recurring_job_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CallerCredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("caller_credential_id");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cron_expression");

                    b.Property<string>("HangfireJobId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hangfire_job_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<string>("RecurringJobId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recurring_job_id");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("task_name");

                    b.Property<string>("TimeZoneId")
                        .HasColumnType("text")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("service_recurring_job", "scheduler_engine");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.ApplicationUser", b =>
                {
                    b.HasOne("SchedulerEngine.Core.Model.DigitalIdentity", "DigitalIdentity")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("SchedulerEngine.Core.Model.ApplicationUser", "DigitalIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulerEngine.Core.Model.Language", "Language")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DigitalIdentity");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.ContactMedium", b =>
                {
                    b.HasOne("SchedulerEngine.Core.Model.Credential", "Credential")
                        .WithMany("ContactMedia")
                        .HasForeignKey("CredentialId");

                    b.HasOne("SchedulerEngine.Core.Model.Party", "Party")
                        .WithMany("ContactMedium")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.Credential", b =>
                {
                    b.HasOne("SchedulerEngine.Core.Model.DigitalIdentity", "DigitalIdentity")
                        .WithMany("Credentials")
                        .HasForeignKey("DigitalIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DigitalIdentity");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.CredentialCharacteristic", b =>
                {
                    b.HasOne("SchedulerEngine.Core.Model.Credential", "Credential")
                        .WithMany("Characteristics")
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.Customer", b =>
                {
                    b.HasOne("SchedulerEngine.Core.Model.PartyRole", "PartyRole")
                        .WithOne("Customer")
                        .HasForeignKey("SchedulerEngine.Core.Model.Customer", "PartyRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartyRole");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.DigitalIdentity", b =>
                {
                    b.HasOne("SchedulerEngine.Core.Model.PartyRole", "PartyRole")
                        .WithOne("DigitalIdentity")
                        .HasForeignKey("SchedulerEngine.Core.Model.DigitalIdentity", "PartyRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartyRole");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.Individual", b =>
                {
                    b.HasOne("SchedulerEngine.Core.Model.Party", "Party")
                        .WithOne("Individual")
                        .HasForeignKey("SchedulerEngine.Core.Model.Individual", "PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.Organization", b =>
                {
                    b.HasOne("SchedulerEngine.Core.Model.Party", "Party")
                        .WithOne("Organization")
                        .HasForeignKey("SchedulerEngine.Core.Model.Organization", "PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.OrganizationLanguageRel", b =>
                {
                    b.HasOne("SchedulerEngine.Core.Model.Language", "Language")
                        .WithMany("OrganizationLanguageRels")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchedulerEngine.Core.Model.Organization", "Organization")
                        .WithMany("OrganizationLanguageRels")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.PartyRole", b =>
                {
                    b.HasOne("SchedulerEngine.Core.Model.Organization", null)
                        .WithMany("PartyRoles")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("SchedulerEngine.Core.Model.Party", "Party")
                        .WithMany("PartyRoles")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulerEngine.Core.Model.PartyRoleType", "PartyRoleType")
                        .WithMany()
                        .HasForeignKey("PartyRoleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchedulerEngine.Core.Model.PartyRoleType", null)
                        .WithMany("PartyRoles")
                        .HasForeignKey("PartyRoleTypeId1");

                    b.Navigation("Party");

                    b.Navigation("PartyRoleType");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.PartyRoleAccount", b =>
                {
                    b.HasOne("SchedulerEngine.Core.Model.Customer", null)
                        .WithMany("PartyRoleAccounts")
                        .HasForeignKey("CustomerId");

                    b.HasOne("SchedulerEngine.Core.Model.PartyRole", "PartyRole")
                        .WithOne("PartyRoleAccount")
                        .HasForeignKey("SchedulerEngine.Core.Model.PartyRoleAccount", "PartyRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartyRole");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.PartyRoleType", b =>
                {
                    b.HasOne("SchedulerEngine.Core.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.RefreshToken", b =>
                {
                    b.HasOne("SchedulerEngine.Core.Model.ApplicationUser", "ApplicationUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.RelatedParty", b =>
                {
                    b.HasOne("SchedulerEngine.Core.Model.Party", "Party")
                        .WithMany("RelatedParties")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchedulerEngine.Core.Model.Party", "Related")
                        .WithMany()
                        .HasForeignKey("RelatedPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Party");

                    b.Navigation("Related");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.ApplicationUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.Credential", b =>
                {
                    b.Navigation("Characteristics");

                    b.Navigation("ContactMedia");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.Customer", b =>
                {
                    b.Navigation("PartyRoleAccounts");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.DigitalIdentity", b =>
                {
                    b.Navigation("ApplicationUser");

                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.Language", b =>
                {
                    b.Navigation("ApplicationUsers");

                    b.Navigation("OrganizationLanguageRels");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.Organization", b =>
                {
                    b.Navigation("OrganizationLanguageRels");

                    b.Navigation("PartyRoles");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.Party", b =>
                {
                    b.Navigation("ContactMedium");

                    b.Navigation("Individual");

                    b.Navigation("Organization");

                    b.Navigation("PartyRoles");

                    b.Navigation("RelatedParties");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.PartyRole", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("DigitalIdentity");

                    b.Navigation("PartyRoleAccount");
                });

            modelBuilder.Entity("SchedulerEngine.Core.Model.PartyRoleType", b =>
                {
                    b.Navigation("PartyRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
